name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.20.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.2
      - name: Deploy
        run: |
            node ci-cd-deploy.js
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build