name: Test

on:
  pull_request:
    branches:
    - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.20.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.2
      - name: Test
        run: |
            node ci-cd-test.js
